### ISSUE TITLE
Problem with popups in IE

### ISSUE THREAD

**Issue by ray007** [jquery/jquery-mobile#8061]
Probably related to #5814.
I'm using popups to display menus, dialogs, ...

This works fine in all browsers at first, but in IE it soon stops working.
The one error I could find is an exception in _safelyblur, because `currentElement` (called with `this.document[ 0 ].activeElement`) is null:
```
TypeError: Unable to get property 'nodeName' of undefined or null reference
   at _safelyBlur (http://myhost.com/myapp/lib/jquery.mobile/jquery.mobile-1.4.5.js:10889:3)
   at Anonymous function (http://myhost.com/myapp/lib/jquery.mobile/jquery.mobile-1.4.5.js:835:5)
   at _openPrerequisitesComplete (http://myhost.com/myapp/lib/jquery.mobile/jquery.mobile-1.4.5.js:10905:4)
   at Anonymous function (http://myhost.com/myapp/lib/jquery.mobile/jquery.mobile-1.4.5.js:835:5)
   at proxy (http://myhost.com/myapp/lib/jquery-2.1.3.js:512:4)
   at Anonymous function (http://myhost.com/myapp/lib/jquery.mobile/jquery.mobile-1.4.5.js:10787:5)
   at fire (http://myhost.com/myapp/lib/jquery-2.1.3.js:3094:5)
   at self.fireWith (http://myhost.com/myapp/lib/jquery-2.1.3.js:3206:7)
   at Anonymous function (http://myhost.com/...
```
triggered by a call with `$element.popup('open')`.

This all happens in a big application, don't have a small sample yet.
Just hoping someone else has seen something similar and maybe an idea how to deal with it...

**Comment by gabrielschulhof** [comment]
https://github.com/jquery/jquery-mobile/pull/7927 addresses this problem.

**Comment by ray007** [comment]
@gabrielschulhof Thank you very much.
Since the target milestone is `1.5.0` I assume there's no plan for a `1.4.6` with this fix in it?
