### ISSUE TITLE
hashToSelector doesn't correctly handle already escaped characters

### ISSUE THREAD

**Issue by dpolivy** [jquery/jquery-mobile#8547]
It's possible that `hashToSelector` is called with a string that contains characters that are already slash-escaped, e.g. `a\'b\'c`. In this case, it incorrectly double encodes the character, leading to the slash being escaped and the character not being escaped. Thus, when the value is passed as a jQuery selector, it blows up with an error like the following:

````
Uncaught Error: Syntax error, unrecognized expression: [data-url='\/kumipehuyu\?q\=a\\'b\'\c']
    at Function.Sizzle.error (http://code.jquery.com/jquery-1.11.1.js:1473:8)
    at Sizzle.tokenize (http://code.jquery.com/jquery-1.11.1.js:2087:11)
    at Sizzle.compile (http://code.jquery.com/jquery-1.11.1.js:2455:12)
    at Sizzle.select (http://code.jquery.com/jquery-1.11.1.js:2545:16)
    at Function.Sizzle (http://code.jquery.com/jquery-1.11.1.js:879:9)
    at Function.$.find (http://code.jquery.com/mobile/git/jquery.mobile-git.js:1895:18)
    at Function.$.find.matches (http://code.jquery.com/mobile/git/jquery.mobile-git.js:1179:12)
    at Function.jQuery.filter (http://code.jquery.com/jquery-1.11.1.js:2681:15)
    at jQuery.fn.init.jQuery.fn.(anonymous function) [as children] (http://code.jquery.com/jquery-1.11.1.js:3030:17)
    at $.(anonymous function).(anonymous function)._find (http://code.jquery.com/mobile/git/jquery.mobile-git.js:4918:6)
````

Test page to reproduce this: http://jsbin.com/kumipehuyu

One possible fix here is to adjust `hashToSelector` method to decode any slash encoded entities prior to encoding them, just to make sure there is no double encoding. That is, change this line:

https://github.com/jquery/jquery-mobile/blob/e377564aa121d0439a21bc97f7854ee618c3f72d/js/navigation/path.js#L395

To something like this:

	return ( hasHash ? "#" : "" ) + hash.replace(/\\([!"#$%&'()*+,./:;<=>?@[\]^`{|}~])/g, '$1').replace( /([!"#$%&'()*+,./:;<=>?@[\]^`{|}~])/g, "\\$1" );

Anyone see any issues with this change?

**Comment by dpolivy** [comment]
To add to this, it also doesn't handle parameters with double slashes `\\` especially if they are next to an escaped character, e.g. `\\'`. Is there a reason that `\` is not in the list of escaped characters for this method? I think it should also be added to both of my regexps above.
